this experiment are for proving the methode of manualy inverse transform of Principal Component Analysis

In [1]:
# Imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from matplotlib.pyplot import figure
%matplotlib inline

In [2]:
# Load the Dataset
from sklearn.datasets import load_boston

boston_dataset = load_boston() 
# converting bunch data from sklean into pandas DataFrame
boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

c:\users\m477a\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the

In [3]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [4]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


In [5]:
# Standardize the data
from sklearn.preprocessing import StandardScaler

x = StandardScaler().fit_transform(boston)
x = pd.DataFrame(x, columns=boston_dataset.feature_names)

In [6]:
x.shape

(506, 13)

## PCA Sklearn Inverse Transform

In [7]:
from sklearn.decomposition import PCA

# Transform the data
pca = PCA(n_components = 0.9) # we also can remove the n_components parameter
pcat = pca.fit_transform(x)

In [8]:
invers_t = pca.inverse_transform(pcat)

In [9]:
invers_t

array([[-0.34365513,  0.30541694, -0.69725392, ..., -1.4559906 ,
         0.48522105, -0.77499904],
       [-0.43159269, -0.29679339, -0.68143546, ..., -0.13369228,
         0.45897034, -0.29185252],
       [-0.49639761, -0.32795803, -0.84015952, ..., -0.23570688,
         0.38592258, -1.17816832],
       ...,
       [-0.69497248, -1.00201422, -0.21942339, ...,  0.75564637,
         0.52829549, -0.48579308],
       [-0.68233703, -0.97919848, -0.19757883, ...,  0.76720492,
         0.48864985, -0.36684137],
       [-0.65438963, -1.04431523, -0.04852907, ...,  0.75126665,
         0.54572154, -0.07093254]])

In [10]:
invers_t.shape

(506, 13)

## Manual Inverse Transform

In [11]:
# Inverse transform the data MANUALY
# here the formula
# data_reduced = np.dot(data - pca.mean_, pca.components_.T)
# data_original = np.dot(data_reduced, pca.components_) + pca.mean_

# example
# import numpy as np
# from sklearn.decomposition import PCA

# pca = PCA(n_components=3)
# pca.fit(data)

# data_reduced = np.dot(data, pca.components_.T) # transform
# data_original = np.dot(data_reduced, pca.components_) # inverse_transform

In [12]:
data_reduced = np.dot(x - pca.mean_, pca.components_.T)

In [13]:
data_reduced

array([[-2.09829747,  0.77311275,  0.34294273, ..., -0.31533814,
         0.31864075,  0.2958318 ],
       [-1.45725167,  0.59198521, -0.69519931, ...,  0.26422321,
         0.55386126, -0.22366994],
       [-2.07459756,  0.5996394 ,  0.1671216 , ...,  0.44809462,
         0.48455996,  0.10516613],
       ...,
       [-0.31236047,  1.15524644, -0.40859759, ...,  0.46794669,
         0.29411936, -0.63866037],
       [-0.27051907,  1.04136158, -0.58545406, ...,  0.48225947,
         0.27159707, -0.57934447],
       [-0.12580322,  0.76197805, -1.294882  , ...,  0.40147353,
         0.17530965, -0.13338197]])

In [14]:
data_original = np.dot(data_reduced, pca.components_) + pca.mean_

In [15]:
data_original

array([[-0.34365513,  0.30541694, -0.69725392, ..., -1.4559906 ,
         0.48522105, -0.77499904],
       [-0.43159269, -0.29679339, -0.68143546, ..., -0.13369228,
         0.45897034, -0.29185252],
       [-0.49639761, -0.32795803, -0.84015952, ..., -0.23570688,
         0.38592258, -1.17816832],
       ...,
       [-0.69497248, -1.00201422, -0.21942339, ...,  0.75564637,
         0.52829549, -0.48579308],
       [-0.68233703, -0.97919848, -0.19757883, ...,  0.76720492,
         0.48864985, -0.36684137],
       [-0.65438963, -1.04431523, -0.04852907, ...,  0.75126665,
         0.54572154, -0.07093254]])

## conclusion
we can see that the manual and the sklearn pca inverse transform has same result

source [here](https://stackoverflow.com/questions/32750915/pca-inverse-transform-manually)

In [16]:
# further into the components
pca.components_

array([[ 0.2509514 , -0.25631454,  0.34667207,  0.00504243,  0.34285231,
        -0.18924257,  0.3136706 , -0.32154387,  0.31979277,  0.33846915,
         0.20494226, -0.20297261,  0.30975984],
       [-0.31525237, -0.3233129 ,  0.11249291,  0.45482914,  0.21911553,
         0.14933154,  0.31197778, -0.34907   , -0.27152094, -0.23945365,
        -0.30589695,  0.23855944, -0.07432203],
       [ 0.24656649,  0.29585782, -0.01594592,  0.28978082,  0.12096411,
         0.59396117, -0.01767481, -0.04973627,  0.28725483,  0.22074447,
        -0.32344627, -0.3001459 , -0.26700025],
       [ 0.06177071,  0.12871159,  0.01714571,  0.81594136, -0.12822614,
        -0.28059184, -0.17520603,  0.21543585,  0.13234996,  0.10333509,
         0.28262198,  0.1684985 ,  0.06941441],
       [ 0.08215692,  0.32061699, -0.00781119,  0.08653094,  0.13685356,
        -0.4234472 ,  0.01669085,  0.09859225, -0.20413162, -0.13046057,
        -0.58400223, -0.34560695,  0.39456113],
       [-0.21965961, -0.323388

In [17]:
pca.components_.shape

(8, 13)

In [18]:
pca.mean_

array([-8.78743718e-17, -6.34319123e-16, -2.68291099e-15,  4.70199198e-16,
        2.49032240e-15, -1.14523016e-14, -1.40785495e-15,  9.21090169e-16,
        5.44140929e-16, -8.86861950e-16, -9.20563581e-15,  8.16310129e-15,
       -3.37016317e-16])

In [19]:
pca.mean_.shape

(13,)