this experiment are intend for comparing the manual eigen value and eigen vector and the sklearn module in PCA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston_dataset = load_boston()

c:\users\m477a\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the

In [4]:
boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

In [5]:
boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [6]:
boston.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [7]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


## Base on the Sklearn Model

Standard scaler [here](https://stackoverflow.com/questions/40758562/can-anyone-explain-me-standardscaler)

In [8]:
# standardize the data
from sklearn.preprocessing import StandardScaler

x = StandardScaler().fit_transform(boston)
x = pd.DataFrame(x, columns=boston_dataset.feature_names)

In [9]:
## PCA
from sklearn.decomposition import PCA

pca = PCA()
pcat = pca.fit_transform(x)

In [10]:
pcat.shape

(506, 13)

In [11]:
# eigen vectors
pca.components_

array([[ 0.2509514 , -0.25631454,  0.34667207,  0.00504243,  0.34285231,
        -0.18924257,  0.3136706 , -0.32154387,  0.31979277,  0.33846915,
         0.20494226, -0.20297261,  0.30975984],
       [-0.31525237, -0.3233129 ,  0.11249291,  0.45482914,  0.21911553,
         0.14933154,  0.31197778, -0.34907   , -0.27152094, -0.23945365,
        -0.30589695,  0.23855944, -0.07432203],
       [ 0.24656649,  0.29585782, -0.01594592,  0.28978082,  0.12096411,
         0.59396117, -0.01767481, -0.04973627,  0.28725483,  0.22074447,
        -0.32344627, -0.3001459 , -0.26700025],
       [ 0.06177071,  0.12871159,  0.01714571,  0.81594136, -0.12822614,
        -0.28059184, -0.17520603,  0.21543585,  0.13234996,  0.10333509,
         0.28262198,  0.1684985 ,  0.06941441],
       [ 0.08215692,  0.32061699, -0.00781119,  0.08653094,  0.13685356,
        -0.4234472 ,  0.01669085,  0.09859225, -0.20413162, -0.13046057,
        -0.58400223, -0.34560695,  0.39456113],
       [-0.21965961, -0.323388

In [12]:
# eigen values
pca.explained_variance_

array([6.1389812 , 1.43611329, 1.2450773 , 0.85927328, 0.83646904,
       0.65870897, 0.5364162 , 0.39688167, 0.27749173, 0.22067394,
       0.18638271, 0.16963823, 0.06363502])

In [13]:
pca.components_.shape

(13, 13)

In [14]:
pca.explained_variance_.shape

(13,)

## Combine Methode

In [15]:
# manual normalization
Xc = np.array((boston - boston.mean(axis=0))/boston.std(axis=0))
Xc = pd.DataFrame(Xc, columns=boston_dataset.feature_names)

In [16]:
pca2 = PCA()
pcat2 = pca2.fit_transform(Xc)

In [17]:
pcat2.shape

(506, 13)

In [18]:
# eigen vectors combine methode
pca2.components_

array([[ 0.2509514 , -0.25631454,  0.34667207,  0.00504243,  0.34285231,
        -0.18924257,  0.3136706 , -0.32154387,  0.31979277,  0.33846915,
         0.20494226, -0.20297261,  0.30975984],
       [-0.31525237, -0.3233129 ,  0.11249291,  0.45482914,  0.21911553,
         0.14933154,  0.31197778, -0.34907   , -0.27152094, -0.23945365,
        -0.30589695,  0.23855944, -0.07432203],
       [ 0.24656649,  0.29585782, -0.01594592,  0.28978082,  0.12096411,
         0.59396117, -0.01767481, -0.04973627,  0.28725483,  0.22074447,
        -0.32344627, -0.3001459 , -0.26700025],
       [ 0.06177071,  0.12871159,  0.01714571,  0.81594136, -0.12822614,
        -0.28059184, -0.17520603,  0.21543585,  0.13234996,  0.10333509,
         0.28262198,  0.1684985 ,  0.06941441],
       [ 0.08215692,  0.32061699, -0.00781119,  0.08653094,  0.13685356,
        -0.4234472 ,  0.01669085,  0.09859225, -0.20413162, -0.13046057,
        -0.58400223, -0.34560695,  0.39456113],
       [-0.21965961, -0.323388

In [19]:
# eigen values combine methode
pca2.explained_variance_

array([6.12684883, 1.43327512, 1.24261667, 0.85757511, 0.83481594,
       0.65740718, 0.53535609, 0.39609731, 0.27694333, 0.22023782,
       0.18601437, 0.16930298, 0.06350926])

## Manual Methode

In [20]:
# normalize the data
X = np.array((boston - boston.mean(axis=0))/boston.std(axis=0))

In [21]:
# X

In [22]:
# calculating the the covariance matrix of the data
Cx = np.cov(X, rowvar=False)

In [23]:
L, P = np.linalg.eig(Cx)

In [24]:
# eigen vector
P

array([[-0.2509514 ,  0.31525237, -0.24656649, -0.06177071,  0.08215692,
         0.21965961, -0.77760721, -0.15335048, -0.0459523 , -0.26039028,
         0.08676107,  0.10964435, -0.01936913],
       [ 0.25631454,  0.3233129 , -0.29585782, -0.12871159,  0.32061699,
         0.3233881 ,  0.27499628,  0.40268031,  0.08091897, -0.35813749,
        -0.07142528, -0.26275629, -0.26752723],
       [-0.34667207, -0.11249291,  0.01594592, -0.01714571, -0.00781119,
         0.0761379 ,  0.33957645, -0.17393172,  0.25107654, -0.64441615,
        -0.11319963,  0.30316943,  0.36353226],
       [-0.00504243, -0.45482914, -0.28978082, -0.81594136,  0.08653094,
        -0.16749014, -0.07413621,  0.02466215, -0.03592171,  0.01372777,
        -0.00398268, -0.01392667,  0.00618184],
       [-0.34285231, -0.21911553, -0.12096411,  0.12822614,  0.13685356,
         0.15298267,  0.19963484, -0.08012056, -0.04363045,  0.01852201,
         0.80432257, -0.11131888, -0.23105645],
       [ 0.18924257, -0.149331

In [25]:
# eigen values
L

array([6.12684883, 1.43327512, 1.24261667, 0.85757511, 0.83481594,
       0.65740718, 0.53535609, 0.39609731, 0.06350926, 0.27694333,
       0.16930298, 0.18601437, 0.22023782])

In [26]:
P.shape

(13, 13)

In [27]:
L.shape

(13,)

## Comparison of the result

In [28]:
ev1 = pd.DataFrame(pca.components_, columns=range(pca.components_.shape[0]))

In [29]:
# eigen vector model sklearn
ev1

0         1         2         3         4         5         6   \
0   0.250951 -0.256315  0.346672  0.005042  0.342852 -0.189243  0.313671   
1  -0.315252 -0.323313  0.112493  0.454829  0.219116  0.149332  0.311978   
2   0.246566  0.295858 -0.015946  0.289781  0.120964  0.593961 -0.017675   
3   0.061771  0.128712  0.017146  0.815941 -0.128226 -0.280592 -0.175206   
4   0.082157  0.320617 -0.007811  0.086531  0.136854 -0.423447  0.016691   
5  -0.219660 -0.323388 -0.076138  0.167490 -0.152983  0.059267 -0.071709   
6   0.777607 -0.274996 -0.339576  0.074136 -0.199635  0.063940  0.116011   
7   0.153350 -0.402680  0.173932 -0.024662  0.080121 -0.326752 -0.600823   
8   0.260390  0.358137  0.644416 -0.013728 -0.018522  0.047898 -0.067562   
9   0.019369  0.267527 -0.363532 -0.006182  0.231056 -0.431420  0.362779   
10 -0.109644  0.262756 -0.303169  0.013927  0.111319  0.053162 -0.459159   
11  0.086761 -0.071425 -0.113200 -0.003983  0.804323  0.152873 -0.211936   
12  0.045952 -0.080919 -0.251077  0.035922  0.043630  0.045567 -0.038551   

          7         8         9         10        11        12  
0  -0.321544  0.319793  0.338469  0.204942 -0.202973  0.309760  
1  -0.349070 -0.271521 -0.239454 -0.305897  0.238559 -0.074322  
2  -0.049736  0.287255  0.220744 -0.323446 -0.300146 -0.267000  
3   0.215436  0.132350  0.103335  0.282622  0.168498  0.069414  
4   0.098592 -0.204132 -0.130461 -0.584002 -0.345607  0.394561  
5   0.023439 -0.143194 -0.192934  0.273153 -0.803455 -0.053216  
6  -0.103900 -0.137943 -0.314887  0.002324  0.070295  0.087011  
7  -0.121812  0.080358  0.082774 -0.317884 -0.004923 -0.424353  
8  -0.153291 -0.470891 -0.176563  0.254428 -0.044898 -0.195221  
9  -0.171213  0.021909 -0.035168  0.153430 -0.096515 -0.600711  
10 -0.695693  0.036544 -0.104836  0.174505  0.019275  0.271382  
11  0.390941 -0.107026 -0.215191  0.209599  0.041723  0.055226  
12 -0.018299 -0.633490  0.720233  0.023398 -0.004463  0.024432

In [30]:
# eigen vector (combination)
ev2 = pd.DataFrame(pca2.components_, columns=range(pca2.components_.shape[0]))

In [31]:
ev2

0         1         2         3         4         5         6   \
0   0.250951 -0.256315  0.346672  0.005042  0.342852 -0.189243  0.313671   
1  -0.315252 -0.323313  0.112493  0.454829  0.219116  0.149332  0.311978   
2   0.246566  0.295858 -0.015946  0.289781  0.120964  0.593961 -0.017675   
3   0.061771  0.128712  0.017146  0.815941 -0.128226 -0.280592 -0.175206   
4   0.082157  0.320617 -0.007811  0.086531  0.136854 -0.423447  0.016691   
5  -0.219660 -0.323388 -0.076138  0.167490 -0.152983  0.059267 -0.071709   
6   0.777607 -0.274996 -0.339576  0.074136 -0.199635  0.063940  0.116011   
7   0.153350 -0.402680  0.173932 -0.024662  0.080121 -0.326752 -0.600823   
8   0.260390  0.358137  0.644416 -0.013728 -0.018522  0.047898 -0.067562   
9   0.019369  0.267527 -0.363532 -0.006182  0.231056 -0.431420  0.362779   
10 -0.109644  0.262756 -0.303169  0.013927  0.111319  0.053162 -0.459159   
11  0.086761 -0.071425 -0.113200 -0.003983  0.804323  0.152873 -0.211936   
12  0.045952 -0.080919 -0.251077  0.035922  0.043630  0.045567 -0.038551   

          7         8         9         10        11        12  
0  -0.321544  0.319793  0.338469  0.204942 -0.202973  0.309760  
1  -0.349070 -0.271521 -0.239454 -0.305897  0.238559 -0.074322  
2  -0.049736  0.287255  0.220744 -0.323446 -0.300146 -0.267000  
3   0.215436  0.132350  0.103335  0.282622  0.168498  0.069414  
4   0.098592 -0.204132 -0.130461 -0.584002 -0.345607  0.394561  
5   0.023439 -0.143194 -0.192934  0.273153 -0.803455 -0.053216  
6  -0.103900 -0.137943 -0.314887  0.002324  0.070295  0.087011  
7  -0.121812  0.080358  0.082774 -0.317884 -0.004923 -0.424353  
8  -0.153291 -0.470891 -0.176563  0.254428 -0.044898 -0.195221  
9  -0.171213  0.021909 -0.035168  0.153430 -0.096515 -0.600711  
10 -0.695693  0.036544 -0.104836  0.174505  0.019275  0.271382  
11  0.390941 -0.107026 -0.215191  0.209599  0.041723  0.055226  
12 -0.018299 -0.633490  0.720233  0.023398 -0.004463  0.024432

In [32]:
# eigen vector manual
ev3 = pd.DataFrame(P, columns=range(P.shape[0]))

In [39]:
ev3

0         1         2         3         4         5         6   \
0  -0.250951  0.315252 -0.246566 -0.061771  0.082157  0.219660 -0.777607   
1   0.256315  0.323313 -0.295858 -0.128712  0.320617  0.323388  0.274996   
2  -0.346672 -0.112493  0.015946 -0.017146 -0.007811  0.076138  0.339576   
3  -0.005042 -0.454829 -0.289781 -0.815941  0.086531 -0.167490 -0.074136   
4  -0.342852 -0.219116 -0.120964  0.128226  0.136854  0.152983  0.199635   
5   0.189243 -0.149332 -0.593961  0.280592 -0.423447 -0.059267 -0.063940   
6  -0.313671 -0.311978  0.017675  0.175206  0.016691  0.071709 -0.116011   
7   0.321544  0.349070  0.049736 -0.215436  0.098592 -0.023439  0.103900   
8  -0.319793  0.271521 -0.287255 -0.132350 -0.204132  0.143194  0.137943   
9  -0.338469  0.239454 -0.220744 -0.103335 -0.130461  0.192934  0.314887   
10 -0.204942  0.305897  0.323446 -0.282622 -0.584002 -0.273153 -0.002324   
11  0.202973 -0.238559  0.300146 -0.168498 -0.345607  0.803455 -0.070295   
12 -0.309760  0.074322  0.267000 -0.069414  0.394561  0.053216 -0.087011   

          7         8         9         10        11        12  
0  -0.153350 -0.045952 -0.260390  0.086761  0.109644 -0.019369  
1   0.402680  0.080919 -0.358137 -0.071425 -0.262756 -0.267527  
2  -0.173932  0.251077 -0.644416 -0.113200  0.303169  0.363532  
3   0.024662 -0.035922  0.013728 -0.003983 -0.013927  0.006182  
4  -0.080121 -0.043630  0.018522  0.804323 -0.111319 -0.231056  
5   0.326752 -0.045567 -0.047898  0.152873 -0.053162  0.431420  
6   0.600823  0.038551  0.067562 -0.211936  0.459159 -0.362779  
7   0.121812  0.018299  0.153291  0.390941  0.695693  0.171213  
8  -0.080358  0.633490  0.470891 -0.107026 -0.036544 -0.021909  
9  -0.082774 -0.720233  0.176563 -0.215191  0.104836  0.035168  
10  0.317884 -0.023398 -0.254428  0.209599 -0.174505 -0.153430  
11  0.004923  0.004463  0.044898  0.041723 -0.019275  0.096515  
12  0.424353 -0.024432  0.195221  0.055226 -0.271382  0.600711

In [38]:
-(ev3.T)
# so actually the sklearn pca has same result if we do transpose and 
# multiple it with minus(subrraction)

0         1         2         3         4         5         6   \
0   0.250951 -0.256315  0.346672  0.005042  0.342852 -0.189243  0.313671   
1  -0.315252 -0.323313  0.112493  0.454829  0.219116  0.149332  0.311978   
2   0.246566  0.295858 -0.015946  0.289781  0.120964  0.593961 -0.017675   
3   0.061771  0.128712  0.017146  0.815941 -0.128226 -0.280592 -0.175206   
4  -0.082157 -0.320617  0.007811 -0.086531 -0.136854  0.423447 -0.016691   
5  -0.219660 -0.323388 -0.076138  0.167490 -0.152983  0.059267 -0.071709   
6   0.777607 -0.274996 -0.339576  0.074136 -0.199635  0.063940  0.116011   
7   0.153350 -0.402680  0.173932 -0.024662  0.080121 -0.326752 -0.600823   
8   0.045952 -0.080919 -0.251077  0.035922  0.043630  0.045567 -0.038551   
9   0.260390  0.358137  0.644416 -0.013728 -0.018522  0.047898 -0.067562   
10 -0.086761  0.071425  0.113200  0.003983 -0.804323 -0.152873  0.211936   
11 -0.109644  0.262756 -0.303169  0.013927  0.111319  0.053162 -0.459159   
12  0.019369  0.267527 -0.363532 -0.006182  0.231056 -0.431420  0.362779   

          7         8         9         10        11        12  
0  -0.321544  0.319793  0.338469  0.204942 -0.202973  0.309760  
1  -0.349070 -0.271521 -0.239454 -0.305897  0.238559 -0.074322  
2  -0.049736  0.287255  0.220744 -0.323446 -0.300146 -0.267000  
3   0.215436  0.132350  0.103335  0.282622  0.168498  0.069414  
4  -0.098592  0.204132  0.130461  0.584002  0.345607 -0.394561  
5   0.023439 -0.143194 -0.192934  0.273153 -0.803455 -0.053216  
6  -0.103900 -0.137943 -0.314887  0.002324  0.070295  0.087011  
7  -0.121812  0.080358  0.082774 -0.317884 -0.004923 -0.424353  
8  -0.018299 -0.633490  0.720233  0.023398 -0.004463  0.024432  
9  -0.153291 -0.470891 -0.176563  0.254428 -0.044898 -0.195221  
10 -0.390941  0.107026  0.215191 -0.209599 -0.041723 -0.055226  
11 -0.695693  0.036544 -0.104836  0.174505  0.019275  0.271382  
12 -0.171213  0.021909 -0.035168  0.153430 -0.096515 -0.600711

In [34]:
# eigen values model sklearn
pca.explained_variance_

array([6.1389812 , 1.43611329, 1.2450773 , 0.85927328, 0.83646904,
       0.65870897, 0.5364162 , 0.39688167, 0.27749173, 0.22067394,
       0.18638271, 0.16963823, 0.06363502])

In [35]:
# eigen values model sklearn with manual normalization (combination)
pca2.explained_variance_

array([6.12684883, 1.43327512, 1.24261667, 0.85757511, 0.83481594,
       0.65740718, 0.53535609, 0.39609731, 0.27694333, 0.22023782,
       0.18601437, 0.16930298, 0.06350926])

In [36]:
# eigen values manual
L

array([6.12684883, 1.43327512, 1.24261667, 0.85757511, 0.83481594,
       0.65740718, 0.53535609, 0.39609731, 0.06350926, 0.27694333,
       0.16930298, 0.18601437, 0.22023782])

### Conclusion
so from the experiment we can get several conclusion which,
- the sklearn preprocessing standardization making the the sklearn pca resulting different with the manual process
- even the result of combination of eigen values are same with manual process the eigen vector are not the same with the manual process and it's more look like with the sklearn pca 