In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train_normal = pd.read_csv('./data/normal_training.csv')

In [3]:
# the data 
x = train_normal[train_normal.simulationRun==1].iloc[:,3:]

In [4]:
x.head()

xmeas_1  xmeas_2  xmeas_3  xmeas_4  xmeas_5  xmeas_6  xmeas_7  xmeas_8  \
0  0.25038   3674.0   4529.0   9.2320   26.889   42.402   2704.3   74.863   
1  0.25109   3659.4   4556.6   9.4264   26.721   42.576   2705.0   75.000   
2  0.25038   3660.3   4477.8   9.4426   26.875   42.070   2706.2   74.771   
3  0.24977   3661.3   4512.1   9.4776   26.758   42.063   2707.2   75.224   
4  0.29405   3679.0   4497.0   9.3381   26.889   42.650   2705.1   75.388   

   xmeas_9  xmeas_10  ...   xmv_2   xmv_3   xmv_4   xmv_5   xmv_6   xmv_7  \
0   120.41   0.33818  ...  53.744  24.657  62.544  22.137  39.935  42.323   
1   120.41   0.33620  ...  53.414  24.588  59.259  22.084  40.176  38.554   
2   120.42   0.33563  ...  54.357  24.666  61.275  22.380  40.244  38.990   
3   120.39   0.33553  ...  53.946  24.725  59.856  22.277  40.257  38.072   
4   120.39   0.32632  ...  53.658  28.797  60.717  21.947  39.144  41.955   

    xmv_8   xmv_9  xmv_10  xmv_11  
0  47.757  47.510  41.258  18.447  
1  43.692  47.427  41.359  17.194  
2  46.699  47.468  41.199  20.530  
3  47.541  47.658  41.643  18.089  
4  47.645  47.346  41.507  18.461  

[5 rows x 52 columns]

In [5]:
# pip install MDP

In [6]:
# pip install mdp

In [7]:
# pip install sklearn-sfa

### MDP nodes

documentation [here](https://mdp-toolkit.github.io/api/mdp.nodes.SFANode-class.html)

In [5]:
import mdp

In [6]:
sfa_mdp = mdp.nodes.SFANode()

In [7]:
x_arr = x.to_numpy()

In [8]:
# transformed data 
slw_mdp = sfa_mdp.execute(x_arr) 
# need to be ndarray type not dataframe pandas

In [9]:
slw_mdp.shape

(500, 52)

In [10]:
sfa_mdp.d
# Delta values corresponding to the 
# SFA components (generalized eigenvalues)

array([0.00487112, 0.01571687, 0.0458013 , 0.17420306, 0.24654455,
       0.26630531, 0.33229181, 0.34403043, 0.42362026, 0.44441458,
       0.47172056, 0.50539072, 0.51880153, 0.58699937, 0.78107   ,
       0.84025394, 0.87041057, 0.93495258, 0.97605678, 1.03221422,
       1.05305495, 1.10807335, 1.12299612, 1.14488413, 1.26605999,
       1.33813469, 1.38829501, 1.49870622, 1.55379822, 1.63992729,
       1.67672126, 1.68330124, 1.73669476, 1.7994772 , 1.85794044,
       1.89598278, 1.93228443, 2.04156394, 2.06526308, 2.08566136,
       2.11402723, 2.15639672, 2.20257404, 2.23733235, 2.31627015,
       2.36494781, 2.39702505, 2.45733563, 2.5212554 , 2.60673594,
       3.02135107, 3.25333792])

In [12]:
sfa_mdp.d.shape

(52,)

In [11]:
sfa_mdp.sf

array([[-1.56637471e-01, -2.19281698e-01,  4.85266394e+00, ...,
        -3.18693507e+01, -2.79637827e-01, -2.37544250e+01],
       [-6.99880322e-05, -1.11287616e-03, -1.54827082e-03, ...,
        -1.40271443e-02,  1.62620421e-02,  1.73678734e-03],
       [-2.27049662e-05,  3.13223424e-05, -1.03623680e-03, ...,
        -8.02734168e-03, -1.28707864e-03, -4.22387655e-04],
       ...,
       [-2.62800776e-01,  2.29859773e-01, -7.77215550e-02, ...,
         1.25759823e-01,  1.33922823e-01,  1.30627784e-01],
       [ 4.33191630e-03, -3.11632552e-04, -1.79311455e-04, ...,
        -1.91246786e-01, -3.84589890e-01, -1.28766577e+00],
       [-1.71676425e+00, -7.76069065e+00,  2.97857821e+01, ...,
        -3.52532483e+00, -3.81165886e-01,  3.93094718e-01]])

In [13]:
sfa_mdp.sf.shape

(52, 52)

## skfa 

documentation [here](https://sklearn-sfa.readthedocs.io/en/latest/generated/sksfa.SFA.html)

how to install [here](https://pypi.org/project/sklearn-sfa/)

In [14]:
from sksfa import SFA

In [15]:
sfa = SFA()

In [16]:
sfat = sfa.fit_transform(x)

In [17]:
sfat.shape

(500, 52)

In [18]:
sfa.delta_values_
# here is the the estimated delta values (mean squared time-difference)
# of the different components

array([0.00486171, 0.01571633, 0.04578785, 0.17419203, 0.24654432,
       0.26630523, 0.33229031, 0.34401537, 0.42362021, 0.44441359,
       0.47171715, 0.50538802, 0.51880086, 0.58699806, 0.78106762,
       0.84025334, 0.8704096 , 0.93495251, 0.97604734, 1.03219938,
       1.05305494, 1.10807208, 1.1229825 , 1.1448597 , 1.26605458,
       1.33812655, 1.3882803 , 1.49870623, 1.55378678, 1.63992005,
       1.67672151, 1.68329745, 1.73668443, 1.7994791 , 1.85793778,
       1.8959761 , 1.93227305, 2.04152587, 2.06523639, 2.08566186,
       2.11402753, 2.15639552, 2.20254492, 2.23732949, 2.31626959,
       2.36494984, 2.39701878, 2.4573292 , 2.52125432, 2.6067328 ,
       3.02134796, 3.25333707])

In [19]:
len(sfa.delta_values_)

52

In [20]:
type(sfa.delta_values_)

numpy.ndarray

In [21]:
sfa.input_dim_
# The number of input features.

52

In [22]:
sfa.n_nontrivial_components_
# The number of components that did not fall under the threshold
# defined by robustness_cutoff. Read a: effective dimension of

52

In [23]:
d = sfa.delta_values_

In [24]:
d

array([0.00486171, 0.01571633, 0.04578785, 0.17419203, 0.24654432,
       0.26630523, 0.33229031, 0.34401537, 0.42362021, 0.44441359,
       0.47171715, 0.50538802, 0.51880086, 0.58699806, 0.78106762,
       0.84025334, 0.8704096 , 0.93495251, 0.97604734, 1.03219938,
       1.05305494, 1.10807208, 1.1229825 , 1.1448597 , 1.26605458,
       1.33812655, 1.3882803 , 1.49870623, 1.55378678, 1.63992005,
       1.67672151, 1.68329745, 1.73668443, 1.7994791 , 1.85793778,
       1.8959761 , 1.93227305, 2.04152587, 2.06523639, 2.08566186,
       2.11402753, 2.15639552, 2.20254492, 2.23732949, 2.31626959,
       2.36494984, 2.39701878, 2.4573292 , 2.52125432, 2.6067328 ,
       3.02134796, 3.25333707])

In [25]:
d.T

array([0.00486171, 0.01571633, 0.04578785, 0.17419203, 0.24654432,
       0.26630523, 0.33229031, 0.34401537, 0.42362021, 0.44441359,
       0.47171715, 0.50538802, 0.51880086, 0.58699806, 0.78106762,
       0.84025334, 0.8704096 , 0.93495251, 0.97604734, 1.03219938,
       1.05305494, 1.10807208, 1.1229825 , 1.1448597 , 1.26605458,
       1.33812655, 1.3882803 , 1.49870623, 1.55378678, 1.63992005,
       1.67672151, 1.68329745, 1.73668443, 1.7994791 , 1.85793778,
       1.8959761 , 1.93227305, 2.04152587, 2.06523639, 2.08566186,
       2.11402753, 2.15639552, 2.20254492, 2.23732949, 2.31626959,
       2.36494984, 2.39701878, 2.4573292 , 2.52125432, 2.6067328 ,
       3.02134796, 3.25333707])

In [26]:
T = d.T*d

In [27]:
T

array([2.36362479e-05, 2.47003176e-04, 2.09652730e-03, 3.03428627e-02,
       6.07841032e-02, 7.09184756e-02, 1.10416851e-01, 1.18346573e-01,
       1.79454078e-01, 1.97503435e-01, 2.22517065e-01, 2.55417055e-01,
       2.69154333e-01, 3.44566728e-01, 6.10066631e-01, 7.06025681e-01,
       7.57612871e-01, 8.74136203e-01, 9.52668409e-01, 1.06543556e+00,
       1.10892472e+00, 1.22782375e+00, 1.26108969e+00, 1.31070373e+00,
       1.60289421e+00, 1.79058267e+00, 1.92732220e+00, 2.24612037e+00,
       2.41425336e+00, 2.68933777e+00, 2.81139501e+00, 2.83349032e+00,
       3.01607282e+00, 3.23812502e+00, 3.45193279e+00, 3.59472537e+00,
       3.73367912e+00, 4.16782787e+00, 4.26520134e+00, 4.34998537e+00,
       4.46911241e+00, 4.65004162e+00, 4.85120412e+00, 5.00564323e+00,
       5.36510481e+00, 5.59298776e+00, 5.74569902e+00, 6.03846682e+00,
       6.35672335e+00, 6.79505587e+00, 9.12854347e+00, 1.05842021e+01])

In [28]:
T.shape

(52,)