In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston_dataset = load_boston()

c:\users\m477a\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the

In [4]:
boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

In [5]:
# standardize the data
from sklearn.preprocessing import StandardScaler

x = StandardScaler().fit_transform(boston)
x = pd.DataFrame(x, columns=boston_dataset.feature_names)

In [6]:
## PCA, IPCA, KPCA
from sklearn.decomposition import KernelPCA

### kernel = linear

In [7]:
# kernel = linear
kpca1 = KernelPCA(n_components=13, remove_zero_eig=True, kernel='linear')
kpcat1 = kpca1.fit_transform(x)

In [8]:
# eigen vectors kpca
kpca1_evtr = kpca1.eigenvectors_

In [9]:
# eigen values kpca
kpca1_evls = kpca1.eigenvalues_

In [10]:
kpca1_evtr.shape

(506, 13)

In [11]:
kpca1_evls.shape

(13,)

In [12]:
kpca1_evtr

array([[-0.03768541,  0.02870799,  0.01367659, ..., -0.0034015 ,
         0.00210036,  0.06455918],
       [-0.02617223,  0.02198218, -0.02772461, ..., -0.06605119,
        -0.0135914 , -0.01247514],
       [-0.03725976,  0.02226641,  0.00666482, ..., -0.0502547 ,
         0.01440486, -0.00247349],
       ...,
       [-0.00560999,  0.04289776, -0.01629491, ...,  0.01192123,
         0.03046395,  0.01102053],
       [-0.00485852,  0.03866887, -0.02334796, ...,  0.00896877,
         0.03259635,  0.00959102],
       [-0.00225942,  0.02829453, -0.05164001, ...,  0.01899881,
         0.02514495,  0.00347668]])

### kernel = poly

In [13]:
# kernel = poly
kpca2 = KernelPCA(n_components=13, remove_zero_eig=True, kernel='poly')
kpcat2 = kpca2.fit_transform(x)

In [14]:
# eigen vectors kpca
kpca2_evtr = kpca2.eigenvectors_

In [15]:
# eigen values kpca
kpca2_evls = kpca2.eigenvalues_

In [16]:
kpca2_evtr.shape

(506, 13)

In [17]:
kpca2_evls.shape

(13,)

In [18]:
kpca2_evtr

array([[-0.01548654,  0.01971785,  0.01029999, ..., -0.02072665,
        -0.0123265 , -0.04100565],
       [-0.01343198,  0.00875119,  0.02301762, ..., -0.0127424 ,
         0.00887524, -0.01552852],
       [-0.01509857,  0.01660209,  0.01645813, ...,  0.01234741,
        -0.01080036,  0.02715904],
       ...,
       [-0.01087604, -0.00285792,  0.03217201, ..., -0.00337109,
         0.05580319,  0.03898563],
       [-0.01074445, -0.00320404,  0.03176485, ..., -0.00801938,
         0.04997927,  0.03585072],
       [-0.01039727, -0.00453133,  0.03168376, ..., -0.02378314,
         0.03125155,  0.03035858]])

### kernel = sigmoid

In [19]:
# kernel = sigmoid
kpca3 = KernelPCA(n_components=13, remove_zero_eig=True, kernel='sigmoid')
kpcat3 = kpca3.fit_transform(x)

In [20]:
# eigen vectors kpca
kpca3_evtr = kpca3.eigenvectors_

In [21]:
# eigen values kpca
kpca3_evls = kpca3.eigenvalues_

In [22]:
kpca3_evtr.shape

(506, 13)

In [23]:
kpca3_evls.shape

(13,)

In [24]:
kpca3_evtr

array([[-0.03970687,  0.03161174,  0.04726238, ...,  0.03666908,
        -0.07782892,  0.05501544],
       [-0.02702175, -0.0020052 ,  0.02839983, ..., -0.04201387,
        -0.01351592,  0.01720977],
       [-0.04059063,  0.03339362, -0.01554216, ..., -0.02686872,
        -0.03682709,  0.00402737],
       ...,
       [-0.00358344,  0.03143545, -0.02668261, ...,  0.05280845,
        -0.01056535,  0.04800545],
       [-0.00266147,  0.02157265, -0.02113996, ...,  0.05331658,
        -0.00350654,  0.05001724],
       [ 0.00045   , -0.01370801,  0.00014444, ...,  0.04940868,
        -0.00363503,  0.03156971]])

#### Dual_coef_

In [25]:
kpca4 = KernelPCA(n_components=10, remove_zero_eig=True, kernel='linear', fit_inverse_transform=True)
kpcat4 = kpca4.fit_transform(x)

In [26]:
kpcat4.shape

(506, 10)

In [27]:
kpca4.dual_coef_

array([[ 0.0223771 , -0.03979026, -0.08833088, ...,  0.0044608 ,
        -0.00150114, -0.0024264 ],
       [ 0.05628909, -0.15502382,  0.2242211 , ..., -0.13949362,
        -0.01719918, -0.18236409],
       [ 0.06500057, -0.13882699,  0.13637031, ..., -0.05704646,
        -0.0038664 , -0.12589288],
       ...,
       [ 0.01550377,  0.00749192, -0.08096722, ...,  0.08610232,
         0.0134535 ,  0.04375469],
       [ 0.01990861, -0.00086686, -0.07263239, ...,  0.08486057,
         0.01366896,  0.03704865],
       [ 0.0016806 ,  0.0323447 , -0.08621776, ...,  0.0859891 ,
         0.0127695 ,  0.0576299 ]])

In [28]:
kpca4.dual_coef_.shape

(506, 13)

## Eigen Solver

In [29]:
# Auto
KpcaESau = KernelPCA(n_components=10, 
                   remove_zero_eig=True, 
                   kernel='linear', 
                   fit_inverse_transform=True,
                   eigen_solver='auto'
                   )
KpcaESaut = KpcaESau.fit_transform(x)

In [30]:
# eigen vectors kpca
KpcaESau_evtr = KpcaESau.eigenvectors_

In [31]:
# eigen values kpca
KpcaESau_evls = KpcaESau.eigenvalues_

In [32]:
KpcaESau_evtr.shape

(506, 10)

In [34]:
KpcaESau_evls.shape

(10,)

In [37]:
# Dense
KpcaESde = KernelPCA(n_components=10, 
                   remove_zero_eig=True, 
                   kernel='linear', 
                   fit_inverse_transform=True,
                   eigen_solver='dense'
                   )
KpcaESdet = KpcaESde.fit_transform(x)

In [38]:
# eigen vectors kpca
KpcaESde_evtr = KpcaESde.eigenvectors_

In [39]:
# eigen values kpca
KpcaESde_evls = KpcaESde.eigenvalues_

In [40]:
KpcaESde_evtr.shape

(506, 10)

In [41]:
KpcaESde_evls.shape

(10,)